# Generated by Django 3.1 on 2020-08-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
